name: Continuous Integration
on: push
jobs:
  test-ubuntu:
    name: Test (Ubuntu)
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Test
      run: |
        docker build --file Dockerfile.testing --tag weasel-testing .
        docker run --rm weasel-testing
  test-macos:
    name: Test (macOS)
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Test
      run: |
        swift package resolve
        swift test --parallel
